### ISSUE TITLE
NODE TARGET problem

### ISSUE THREAD

**Issue by hansenshi** [amousset/php-weathermap-zabbix-plugin#8]
[weathermap]# php ./weathermap --config configs/simple.conf --htmloutput test01.html

WARNING: configs/simple.conf: ProcessTargets: NODE testint01, target: zabbix:key_:SW01:ifOperStatus[10GE1/0/1]: on config line 82 of configs/simple.conf was not recognised as a valid TARGET [WMWARN08]

============
NODE testint01
        LABEL testint01
        TARGET zabbix:key_:SW01:ifOperStatus[10GE1/0/1]
        POSITION 294 446

**Comment by amousset** [comment]
I guess that happens because it expects both output and input item names.

**Comment by hansenshi** [comment]
I found NODE has the problem , the LINK is ok

**Comment by amousset** [comment]
So is there still a bug somewhere?

**Comment by hansenshi** [comment]
I think so , can't not get value
![企业微信截图_15689037809650](https://user-images.githubusercontent.com/19355780/65253913-03308200-db2e-11e9-84e3-2639816b45b1.png)

**Comment by amousset** [comment]
It the error message the same? Do you have added the other value in the `TARGET`?

**Comment by hansenshi** [comment]
same error

I want to get the interface status value, and then display the corresponding color.
==
KEYPOS ifstatus 2 811 IF_Status
KEYSTYLE  ifstatus tags
SCALE ifstatus 1    1      0 255   0  Up
SCALE ifstatus 0    0    240 240   0  Unknown
SCALE ifstatus 2    2    255   0   0  Down

NODE testint01
        LABEL testint01
        TARGET zabbix:key_:SH-GDS304-FAT-SW-009011-H02:ifOperStatus[10GE1/0/1]:
         USESCALE ifstatus in percent
        POSITION 294 446

**Comment by amousset** [comment]
``` TARGET zabbix:key_:SH-GDS304-FAT-SW-009011-H02:ifOperStatus[10GE1/0/1]``` does not match what is in the [docs](https://github.com/amousset/php-weathermap-zabbix-plugin/wiki/Configuration-Reference#target):
```TARGET zabbix:keyname:hostname:input_item_name:output_item_name```, you are lissing the last part, the `output_item_name`. I think this is the cause of the problem. This is an arbitrary limitation, and I would accept a PR making one the the item optional.

**Comment by hansenshi** [comment]
Thanks a lot , I changed the content to the following, the error disappeared.

NODE testint01
        LABEL testint01
        TARGET zabbix:key_:SH-GDS304-FAT-SW-009011-H02:ifOperStatus[10GE1/0/1]:aswill
        USESCALE ifstatus in percent
        POSITION 294 446

**Comment by hansenshi** [comment]
It can display the corresponding  color , Thanks
![企业微信截图_15689037809650](https://user-images.githubusercontent.com/19355780/65258422-7093e100-db35-11e9-9acc-232b472b0cda.png)
